"use client";

import Header from '@/components/Header';
import './globals.css';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import AccountProvider from '@/context/AccountContext';
import Footer from '@/components/Footer';
import Toast from '@/components/Toast';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1,
    }
  }
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-speedy relative text-stone-50 bg-stone-950`}>
        <AccountProvider>
            <QueryClientProvider client={queryClient}>
              <Header/>
              <main className="flex flex-col max-w-7xl mx-auto min-h-[80vh]">
                {children}
              </main>
              <Footer/>
            </QueryClientProvider>
        </AccountProvider>
        <Toast/>
      </body>
    </html>
  )
}
